"""initial_schema

Revision ID: 14c5172e69ee
Revises: 
Create Date: 2026-08-20 07:03:22.226309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c5172e69ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_request_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('request_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_request_logs_feature'), 'ai_request_logs', ['feature'], unique=False)
    op.create_index(op.f('ix_ai_request_logs_organization_id'), 'ai_request_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_request_logs_user_id'), 'ai_request_logs', ['user_id'], unique=False)
    op.create_table('feature_toggles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_toggles_feature_name'), 'feature_toggles', ['feature_name'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('businesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_customers', sa.Text(), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('business_goals', sa.Text(), nullable=True),
    sa.Column('marketing_channels', sa.Text(), nullable=True),
    sa.Column('ai_business_profile', sa.JSON(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('health_analysis', sa.JSON(), nullable=True),
    sa.Column('gbp_account_id', sa.String(length=255), nullable=True),
    sa.Column('gbp_location_id', sa.String(length=255), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_organization_id'), 'businesses', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OWNER', 'MANAGER', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('business_analytics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('profile_views', sa.Integer(), nullable=True),
    sa.Column('website_clicks', sa.Integer(), nullable=True),
    sa.Column('phone_calls', sa.Integer(), nullable=True),
    sa.Column('direction_requests', sa.Integer(), nullable=True),
    sa.Column('photo_views', sa.Integer(), nullable=True),
    sa.Column('ai_performance_summary', sa.Text(), nullable=True),
    sa.Column('ai_insights', sa.JSON(), nullable=True),
    sa.Column('what_worked', sa.Text(), nullable=True),
    sa.Column('what_did_not_work', sa.Text(), nullable=True),
    sa.Column('next_actions', sa.Text(), nullable=True),
    sa.Column('raw_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_analytics_business_id'), 'business_analytics', ['business_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('offer', sa.Text(), nullable=True),
    sa.Column('messaging', sa.Text(), nullable=False),
    sa.Column('cta', sa.String(length=500), nullable=False),
    sa.Column('content_ideas', sa.JSON(), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', name='campaignstatus'), nullable=False),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_business_id'), 'campaigns', ['business_id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('comparison_insights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_business_id'), 'competitors', ['business_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('notification_type', sa.Enum('NEW_REVIEW', 'PROBLEM', 'OPPORTUNITY', 'ANALYSIS_COMPLETE', 'RECOMMENDATION', 'CAMPAIGN_UPDATE', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_business_id'), 'notifications', ['business_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('URGENT', 'IMPORTANT', 'OPPORTUNITY', name='recommendationpriority'), nullable=False),
    sa.Column('impact', sa.String(length=255), nullable=False),
    sa.Column('effort', sa.String(length=255), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('related_feature', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DISMISSED', name='recommendationstatus'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_business_id'), 'recommendations', ['business_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('review_date', sa.String(length=50), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='reviewsentiment'), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('key_themes', sa.Text(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('ai_generated_reply', sa.Text(), nullable=True),
    sa.Column('is_replied', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_business_id'), 'reviews', ['business_id'], unique=False)
    op.create_table('seo_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('keyword_opportunities', sa.JSON(), nullable=True),
    sa.Column('missing_topics', sa.JSON(), nullable=True),
    sa.Column('content_opportunities', sa.JSON(), nullable=True),
    sa.Column('profile_optimizations', sa.JSON(), nullable=True),
    sa.Column('local_presence_analysis', sa.JSON(), nullable=True),
    sa.Column('full_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_analyses_business_id'), 'seo_analyses', ['business_id'], unique=False)
    op.create_table('contents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('content_type', sa.Enum('GOOGLE_POST', 'INSTAGRAM', 'FACEBOOK', 'ADVERTISEMENT', 'WEBSITE', 'SEO_ARTICLE', 'REVIEW_REPLY', name='contenttype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.String(length=255), nullable=True),
    sa.Column('marketing_goal', sa.String(length=255), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('call_to_action', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PUBLISHED', name='contentstatus'), nullable=False),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_business_id'), 'contents', ['business_id'], unique=False)
    op.create_table('creatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('style', sa.String(length=255), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('GENERATING', 'COMPLETED', 'FAILED', name='creativestatus'), nullable=False),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatives_business_id'), 'creatives', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creatives_business_id'), table_name='creatives')
    op.drop_table('creatives')
    op.drop_index(op.f('ix_contents_business_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_seo_analyses_business_id'), table_name='seo_analyses')
    op.drop_table('seo_analyses')
    op.drop_index(op.f('ix_reviews_business_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_recommendations_business_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_business_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_competitors_business_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_campaigns_business_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_business_analytics_business_id'), table_name='business_analytics')
    op.drop_table('business_analytics')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_businesses_organization_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_feature_toggles_feature_name'), table_name='feature_toggles')
    op.drop_table('feature_toggles')
    op.drop_index(op.f('ix_ai_request_logs_user_id'), table_name='ai_request_logs')
    op.drop_index(op.f('ix_ai_request_logs_organization_id'), table_name='ai_request_logs')
    op.drop_index(op.f('ix_ai_request_logs_feature'), table_name='ai_request_logs')
    op.drop_table('ai_request_logs')
    # ### end Alembic commands ###
